version: 2
jobs:
  build:
    docker:
      - image: node:10

    environment:
      NODE_ENV: test

    working_directory: /home/ubuntu/workspace

    parallelism: 1

    steps:
      - checkout

      - restore_cache:
          name: Restore Cache for Packages
          keys:
            - npm-{{ .Branch }}-{{ checksum "package-lock.json" }}
            - npm-{{ .Branch }}-

      - run: npm install --no-emoji --no-progress
      - run: npm run lint
      - run: |
          if [ -n "$COVERALLS_REPO_TOKEN" ] ; then
            npm run test:coverage
            npm run coveralls
          else
            # No coverage for pull request from fork repository
            npm run test
          fi

      - save_cache:
          name: Save Cache for Packages
          key: npm-{{ .Branch }}-{{ checksum "package-lock.json" }}
          paths:
            - /home/ubuntu/workspace/node_modules
