version: 2
jobs:
  build:
    docker:
      - image: node:6.10.0

    environment:
      NODE_ENV: test

    working_directory: /home/ubuntu/workspace

    parallelism: 1

    steps:
      - checkout

      - restore_cache:
          name: Restore Cache for Packages
          keys:
            - npm-{{ .Branch }}-{{ checksum "package-lock.json" }}
            - npm-{{ .Branch }}-

      - run:
          name: Install Dependencies
          command: npm install --no-emoji --no-progress

      - run:
          name: Run Test
          command: npm run test:coverage

      - run:
          name: Report Coverage
          command: npm run coveralls

      - save_cache:
          name: Save Cache for Packages
          key: npm-{{ .Branch }}-{{ checksum "package-lock.json" }}
          paths:
            - /home/ubuntu/workspace/node_modules
