version: 2
jobs:
  build:
    docker:
      - image: node:6.10.0

    environment:
      NODE_ENV: test

    working_directory: /home/ubuntu/workspace

    parallelism: 1

    steps:
      - checkout

      - restore_cache:
          name: Restore Cache for Packages
          keys:
            - npm-{{ .Branch }}-{{ checksum "package-lock.json" }}
            - npm-{{ .Branch }}-

      - run: npm install --no-emoji --no-progress
      - run: npm run lint
      - run: npm run test:coverage
      - run: npm run coveralls

      - save_cache:
          name: Save Cache for Packages
          key: npm-{{ .Branch }}-{{ checksum "package-lock.json" }}
          paths:
            - /home/ubuntu/workspace/node_modules
